### ISSUE TITLE
feat: define `breaking change` label

### ISSUE THREAD

**Issue by alestiago** [VeryGoodOpenSource/.github#11]
We should have a "breaking change" label in our `labels.yml` that is used to label those changes that cause incompatibility in some way with previous versions.

**Comment by tomarra** [comment]
Defined in our [Notion doc](https://www.notion.so/verygoodventures/GitHub-Hygiene-19b56dca518f41819458e061d774319b?pvs=4) and set as a default label in the `VeryGoodOpenSource` org.

- Label Name: breaking change
- Description: A change that will cause existing functionality to change or fail.
- Color Code: #e3846d
