### ISSUE TITLE
feat: define `has reproductive steps` label

### ISSUE THREAD

**Issue by alestiago** [VeryGoodOpenSource/.github#12]
We should have a "has reproductive steps" label in our labels.yml that is used to label with the following description "The issue has been confirmed reproducible and is ready to work on".

**Comment by tomarra** [comment]
Defined in our [Notion doc](https://www.notion.so/verygoodventures/GitHub-Hygiene-19b56dca518f41819458e061d774319b?pvs=4) and set as a default label in the `VeryGoodOpenSource` org

- Label Name: has reproductive steps
- Description: This issue contains detailed steps to reproduce the issue
- Color Code: #3799b8
