### ISSUE TITLE
feat: define `needs reproductive steps` label

### ISSUE THREAD

**Issue by alestiago** [VeryGoodOpenSource/.github#13]
We should have a "needs reproductive steps" label in our labels.yml that is used to label with the following description "The issue has no reproducible steps and is not ready to work on".

**Comment by tomarra** [comment]
Defined in our [Notion doc](https://www.notion.so/verygoodventures/GitHub-Hygiene-19b56dca518f41819458e061d774319b?pvs=4) and set as a default label in the `VeryGoodOpenSource` org

- Label Name: needs reproductive steps
- Description: This issue lacks sufficient details and further information in needed
- Color Code: #910578
