### ISSUE TITLE
feat: define `investigating` label

### ISSUE THREAD

**Issue by alestiago** [VeryGoodOpenSource/.github#15]
We shoulda add the `investigating` label to the labels to define whenever something is currently being investigated.

**Comment by tomarra** [comment]
Defined in our [Notion doc](https://www.notion.so/verygoodventures/GitHub-Hygiene-19b56dca518f41819458e061d774319b?pvs=4) and set as a default label in the `VeryGoodOpenSource` org

- Label Name: investigating
- Description: This is currently being looked into to understand the cause/scope
- Color Code: #ce37f8
